### ISSUE TITLE
Uri.parse coming with strange path

### ISSUE THREAD

**Issue by afucher** [Microsoft/vscode-uri#6]
Hi,
I'm trying to get the absolute path of a file from a URI that the VSCode sends to me.
The URI: `file:///c:/Users/fucher/Desktop/b.prw`  

If I execute the `Uri.parse` I'm getting this output:  
`Uri {  
  _scheme: 'file',  
  _authority: '',  
  _path: '/c:/Users/fucher/Desktop/b.prw',  
  _query: '',  
  _fragment: '',  
  _formatted: null,  
  _fsPath: null }`  

Shouldn't the path be `c:/Users/fucher/Desktop/b.prw` ?

**Comment by kittaakos** [comment]
I have the same issue. According to [this test] case, that is the expected behavior.

[this test]: https://github.com/Microsoft/vscode-uri/blob/master/spec/uri.test.ts#L56

**Comment by jrieken** [comment]
The path of a URI is defined like that (at least that is my reading of the spec). Be careful when looking at `Uri#path` and thinking of file paths. There are subtle differences between them, the obvious is the forward vs backslash but also UNC paths are special because they actually have authority component (the server bit)

Below is some ascii art we took from the spec to clarify components. 

```
        foo://example.com:8042/over/there?name=ferret#nose
        \_/   \______________/\_________/ \_________/ \__/
         |           |            |            |        |
      scheme     authority       path        query   fragment
         |   _____________________|__
        / \ /                        \
        urn:example:animal:ferret:nose
```

The **good** news here is that know of the path-challenge therefore `Uri#fsPath` exists. That is normalised towards the OS you using and knows how to handle UNC paths. Samples

```
// unc file uri, 2 slashes after the protocol
let u  = URI.parse('file://smb/c$/shares/file.txt')
u.fsPath === '\\smb\c$\shares\file.txt'
u.path === '/c$/shares/file.txt`
u.authority === 'smb'

// normal file uri, 3 slashes after the protocol
u = URI.parse('file:///c:/ping/pong')
u.fsPath === 'c:\ping\pong';
u.path === 'c:/ping/pong'
u.authority === ''

```

**Comment by kittaakos** [comment]
Thanks for the answer @jrieken!

Just to make sure we are on the same page:

Regarding the samples and the "assertions" you have provided; not all of them are true, right? Or did I miss something?

```
const URI = require("vscode-uri");

// unc file uri, 2 slashes after the protocol
let u = URI.default.parse('file://smb/c$/shares/file.txt')
console.log(u.fsPath === '\\smb\c$\shares\file.txt') // false
console.log(u.path === '/c$/shares/file.txt') // true
console.log(u.authority === 'smb') // true

// normal file uri, 3 slashes after the protocol
u = URI.default.parse('file:///c:/ping/pong')
console.log(u.fsPath === 'c:\ping\pong') // false
console.log(u.path === 'c:/ping/pong') // false
console.log(u.authority === '') // true
```

**Comment by jrieken** [comment]
The `fsPath` property uses backslashes on windows and forward slashes on *nix. So, the answer depends. The rest should be as stated in my comment above.

<img width="622" alt="screen shot 2017-05-17 at 18 15 40" src="https://cloud.githubusercontent.com/assets/1794099/26164426/e4f82926-3b2c-11e7-9b40-66b93596095e.png">
